In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf
from scipy.stats import norm, t
import matplotlib.pyplot as plt

In [2]:
stockList = ['MSFT', 'AAPL', 'NVDA', 'AMZN', 'META', 'GOOGL']
stocks = [stock for stock in stockList]

In [22]:
endDate = dt.datetime.now()
startDate = endDate - dt.timedelta(days=20)
stockData = yf.download(stocks, start=startDate, end=endDate)

[*********************100%***********************]  6 of 6 completed

In [23]:
stockData.tail(10)

Price            Close                                                  \
Ticker            AAPL        AMZN       GOOGL        META        MSFT
Date
2026-06-26  283.779999  232.690002  337.390015  550.250000  372.970001
2026-06-29  281.739990  240.139999  353.649994  562.599976  368.570007
2026-06-30  289.359985  238.339996  357.369995  563.289978  373.019989
2026-07-01  294.380005  241.699997  361.209991  612.909973  384.279999
2026-07-02  308.630005  242.669998  359.910004  582.900024  390.489990
2026-07-06  312.660004  244.160004  366.459991  600.289978  386.739990
2026-07-07  310.660004  245.979996  367.029999  615.580017  388.839996
2026-07-08  313.390015  243.619995  361.920013  603.119995  383.339996
2026-07-09  316.220001  247.039993  358.890015  631.479980  384.359985
2026-07-10  315.320007  245.339996  357.179993  669.210022  385.100006

Price                         High                                      ...  \
Ticker            NVDA        AAPL        AMZN       GOOGL        META  ...
Date                                                                    ...
2026-06-26  192.529999  285.950012  233.899994  346.359985  556.849976  ...
2026-06-29  194.970001  288.369995  249.710007  354.350006  570.900024  ...
2026-06-30  200.089996  289.940002  241.539993  358.619995  565.539978  ...
2026-07-01  197.580002  296.589996  244.899994  362.970001  628.280029  ...
2026-07-02  194.830002  309.420013  246.720001  364.209991  610.000000  ...
2026-07-06  195.550003  314.200012  246.039993  367.929993  603.580017  ...
2026-07-07  196.929993  315.480011  248.929993  373.160004  625.369995  ...
2026-07-08  204.119995  314.820007  244.800003  367.839996  616.000000  ...
2026-07-09  202.779999  316.529999  247.500000  359.649994  633.270020  ...
2026-07-10  210.960007  316.910004  251.029999  357.820007  677.859985  ...

Price             Open                                         Volume  \
Ticker           GOOGL        META        MSFT        NVDA       AAPL
Date
2026-06-26  342.549988  543.340027  357.149994  193.119995  261775500
2026-06-29  341.829987  560.000000  377.500000  193.850006   66427000
2026-06-30  353.869995  560.940002  371.029999  197.240005   65100200
2026-07-01  358.369995  607.909973  380.829987  196.199997   50164200
2026-07-02  359.480011  607.900024  384.480011  197.139999   75352800
2026-07-06  361.549988  594.840027  387.040009  194.419998   53590000
2026-07-07  369.070007  607.590027  392.489990  192.369995   42490000
2026-07-08  364.760010  614.390015  384.029999  195.179993   41323500
2026-07-09  354.309998  583.989990  374.450012  204.460007   48124500
2026-07-10  357.529999  660.340027  387.799988  202.000000   34109200

Price
Ticker           AMZN      GOOGL      META       MSFT       NVDA
Date
2026-06-26  248372100  114706300  18867700  186201600  179304100
2026-06-29   77619200   34213900  15011400   51229900  148835700
2026-06-30   66228300   35237200  18111100   44945700  166476700
2026-07-01   53829900   26736400  45536300   48065800  146147600
2026-07-02   48246400   25974800  21705900   42128900  142068700
2026-07-06   40044000   26915800  17674100   34224500  108999000
2026-07-07   40579600   24045600  18560800   29297500  124154600
2026-07-08   29653000   22094800  13606500   25908300  147419100
2026-07-09   38091700   24729100  26579700   31083200  132037400
2026-07-10   31624900   18126000  40563100   24612200  148124000

[10 rows x 30 columns]

In [24]:
stockData.swaplevel(axis=1).sort_index(axis=1).tail(10)

Ticker            AAPL                                                 \
Price            Close        High         Low        Open     Volume
Date
2026-06-26  283.779999  285.950012  274.209991  275.000000  261775500
2026-06-29  281.739990  288.369995  279.850006  286.730011   66427000
2026-06-30  289.359985  289.940002  280.700012  281.170013   65100200
2026-07-01  294.380005  296.589996  289.200012  293.440002   50164200
2026-07-02  308.630005  309.420013  293.679993  294.119995   75352800
2026-07-06  312.660004  314.200012  307.000000  307.359985   53590000
2026-07-07  310.660004  315.480011  310.149994  315.290009   42490000
2026-07-08  313.390015  314.820007  307.049988  311.910004   41323500
2026-07-09  316.220001  316.529999  308.160004  310.510010   48124500
2026-07-10  315.320007  316.910004  312.170013  314.720001   34109200

Ticker            AMZN                                                 ...  \
Price            Close        High         Low        Open     Volume  ...
Date                                                                   ...
2026-06-26  232.690002  233.899994  226.130005  227.210007  248372100  ...
2026-06-29  240.139999  249.710007  233.800003  234.220001   77619200  ...
2026-06-30  238.339996  241.539993  237.169998  237.350006   66228300  ...
2026-07-01  241.699997  244.899994  234.899994  239.750000   53829900  ...
2026-07-02  242.669998  246.720001  241.080002  241.610001   48246400  ...
2026-07-06  244.160004  246.039993  240.880005  243.800003   40044000  ...
2026-07-07  245.979996  248.929993  242.699997  246.979996   40579600  ...
2026-07-08  243.619995  244.800003  240.520004  244.270004   29653000  ...
2026-07-09  247.039993  247.500000  238.250000  239.820007   38091700  ...
2026-07-10  245.339996  251.029999  244.410004  249.550003   31624900  ...

Ticker            MSFT                                                 \
Price            Close        High         Low        Open     Volume
Date
2026-06-26  372.970001  376.609985  355.429993  357.149994  186201600
2026-06-29  368.570007  380.500000  359.899994  377.500000   51229900
2026-06-30  373.019989  374.149994  367.450012  371.029999   44945700
2026-07-01  384.279999  388.829987  374.890015  380.829987   48065800
2026-07-02  390.489990  392.200012  383.700012  384.480011   42128900
2026-07-06  386.739990  389.149994  381.220001  387.040009   34224500
2026-07-07  388.839996  395.570007  388.220001  392.489990   29297500
2026-07-08  383.339996  385.309998  381.329987  384.029999   25908300
2026-07-09  384.359985  384.649994  373.350006  374.450012   31083200
2026-07-10  385.100006  391.910004  381.500000  387.799988   24612200

Ticker            NVDA
Price            Close        High         Low        Open     Volume
Date
2026-06-26  192.529999  195.550003  191.220001  193.119995  179304100
2026-06-29  194.970001  196.179993  189.800003  193.850006  148835700
2026-06-30  200.089996  200.630005  195.110001  197.240005  166476700
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.139999  192.369995  124154600
2026-07-08  204.119995  205.160004  195.059998  195.179993  147419100
2026-07-09  202.779999  204.589996  198.960007  204.460007  132037400
2026-07-10  210.960007  211.000000  201.919998  202.000000  148124000

[10 rows x 30 columns]

In [25]:
stockData['Close'].tail(10)

Ticker,AAPL,AMZN,GOOGL,META,MSFT,NVDA
Date,,,,,,
2026-06-26,283.779999,232.690002,337.390015,550.250000,372.970001,192.529999
2026-06-29,281.739990,240.139999,353.649994,562.599976,368.570007,194.970001
2026-06-30,289.359985,238.339996,357.369995,563.289978,373.019989,200.089996
2026-07-01,294.380005,241.699997,361.209991,612.909973,384.279999,197.580002
2026-07-02,308.630005,242.669998,359.910004,582.900024,390.489990,194.830002
2026-07-06,312.660004,244.160004,366.459991,600.289978,386.739990,195.550003
2026-07-07,310.660004,245.979996,367.029999,615.580017,388.839996,196.929993
2026-07-08,313.390015,243.619995,361.920013,603.119995,383.339996,204.119995
2026-07-09,316.220001,247.039993,358.890015,631.479980,384.359985,202.779999
2026-07-10,315.320007,245.339996,357.179993,669.210022,385.100006,210.960007

$$\mathrm{Return}(t)=\frac{\mathrm{Price}(t)-\mathrm{Price}(t-1)}{\mathrm{Price}(t-1)}$$

In [26]:
returns = stockData['Close'].pct_change()
returns.tail(10)

Ticker          AAPL      AMZN     GOOGL      META      MSFT      NVDA
Date
2026-06-26  0.031365  0.025021 -0.018388  0.013594  0.057081 -0.016399
2026-06-29 -0.007189  0.032017  0.048193  0.022444 -0.011797  0.012673
2026-06-30  0.027046 -0.007496  0.010519  0.001226  0.012074  0.026260
2026-07-01  0.017349  0.014098  0.010745  0.088090  0.030186 -0.012544
2026-07-02  0.048407  0.004013 -0.003599 -0.048963  0.016160 -0.013918
2026-07-06  0.013058  0.006140  0.018199  0.029834 -0.009603  0.003696
2026-07-07 -0.006397  0.007454  0.001555  0.025471  0.005430  0.007057
2026-07-08  0.008788 -0.009594 -0.013923 -0.020241 -0.014145  0.036510
2026-07-09  0.009030  0.014038 -0.008372  0.047022  0.002661 -0.006565
2026-07-10 -0.002846 -0.006881 -0.004765  0.059749  0.001925  0.040339

In [27]:
returns.shape

(14, 6)

La cantidad de registros corresponde a la cantidad de días quitando fines de semana y feriados.

In [28]:
mean_returns = returns.mean()
mean_returns

Ticker
AAPL     0.004936
AMZN     0.004167
GOOGL    0.001770
META     0.013900
MSFT     0.003900
NVDA     0.001097
dtype: float64

Para cualquier par de activos (por ejemplo, $X$ para AAPL y $Y$ para AMZN), Pandas aplica la fórmula de la covarianza muestral:
$$\text{cov}(X, Y) = \frac{1}{N - 1} \sum_{i=1}^{N} (x_i - \bar{x})(y_i - \bar{y})$$
Donde: $N$ es el número total de días u observaciones . Se divide entre $N-1$ porque estamos trabajando con una muestra de datos, no con la población completa. $x_i$ e $y_i$ son los rendimientos de cada día para cada acción. $\bar{x}$ y $\bar{y}$ son las medias de los rendimientos de todo el período para esas acciones.

In [29]:
cov_matrix = returns.cov()
cov_matrix

Ticker      AAPL      AMZN     GOOGL      META      MSFT      NVDA
Ticker
AAPL    0.000693  0.000205 -0.000026  0.000046  0.000420  0.000058
AMZN    0.000205  0.000260  0.000108  0.000247  0.000211 -0.000072
GOOGL  -0.000026  0.000108  0.000301  0.000167 -0.000107  0.000085
META    0.000046  0.000247  0.000167  0.001404  0.000260  0.000143
MSFT    0.000420  0.000211 -0.000107  0.000260  0.000573 -0.000162
NVDA    0.000058 -0.000072  0.000085  0.000143 -0.000162  0.000543

In [30]:
# trasforma cov_matrix in a numpy array
cov_matrix_np = cov_matrix.to_numpy()

# calcula determinante de la matriz de covarianza en notacion científica
det_cov_matrix = np.linalg.det(cov_matrix_np)
print(f"Determinante de la matriz de covarianza: {det_cov_matrix:.2e}")

# invierte la matriz de covarianza
inv_cov_matrix = np.linalg.inv(cov_matrix_np)
print(f"Matriz de covarianza invertida:\n{inv_cov_matrix.round(4)}")

# calcula el número de condición de la matriz de covarianza
norma_2 = np.linalg.norm(cov_matrix_np, ord=2)
norma_2_inv = np.linalg.norm(inv_cov_matrix, ord=2)
num_condicion = norma_2 * norma_2_inv
print(f"Número de condición por definición: {num_condicion:.4f}")

# calcula los autovalores de la matriz de covarianza en notación científica
eigenvalues, _ = np.linalg.eigh(cov_matrix_np)
print(f"Autovalores: {eigenvalues.round(4)}")
print(f"Número de condición por autovalores: {eigenvalues.max() / eigenvalues.min():.4f}")

num_condicion = np.linalg.cond(cov_matrix_np)
print(f"Número de condición por función: {num_condicion:.4f}")

Determinante de la matriz de covarianza: 1.95e-21
Matriz de covarianza invertida:
[[ 4177.6798 -2083.9672  -110.1361  1064.2091 -3348.8648 -1981.2708]
 [-2083.9672 11244.031  -5134.8478 -1035.029  -2537.2423  2039.3607]
 [ -110.1361 -5134.8478  6741.5998  -430.9599  3245.9868  -645.5091]
 [ 1064.2091 -1035.029   -430.9599  1241.0821 -1291.4557  -895.46  ]
 [-3348.8648 -2537.2423  3245.9868 -1291.4557  6852.8864  1890.1445]
 [-1981.2708  2039.3607  -645.5091  -895.46    1890.1445  3222.0704]]
Número de condición por definición: 26.5884
Autovalores: [0.0001 0.0001 0.0003 0.0006 0.0011 0.0016]
Número de condición por autovalores: 26.5884
Número de condición por función: 26.5884

In [31]:
import plotly.express as px

# 1. Datos y retornos
stocks = ["MSFT", "AAPL", "NVDA", "AMZN", "META", "GOOGL"]
returns = (
    yf.download(stocks, start=dt.datetime.now() - dt.timedelta(days=300))[
        "Close"
    ]
    .pct_change()
    .dropna()
)

dias, kappa = [], []

# 2. Bucle de número de condición
for d in range(150, 2, -1):
    cov = returns.tail(d).cov().to_numpy()
    ev = np.linalg.eigh(cov)[0]
    k = ev[-1] / ev[0] if ev[0] > 1e-12 else float("inf")
    dias.append(d)
    kappa.append(k)
    if k > 10000:
        print(f"Se alcanzó el umbral en {d} días y kappa={k:.2f}")
        break

# 3. Gráfico minimalista con Plotly Express
fig = px.line(x=dias, y=kappa, log_y=True, markers=True)
fig.add_hline(y=10000, line_dash="dash", line_color="black")
fig.update_layout(
    width=1200,
    height=350,
    xaxis=dict(title="Días hacia atrás", autorange="reversed"),
    yaxis_title="Kappa",
    margin=dict(l=10, r=10, t=10, b=10),
)
fig.show()

[*********************100%***********************]  6 of 6 completed

Se alcanzó el umbral en 7 días y kappa=1928756.32

La diagonal es la varianza de cada activo respectivamente. En finanzas, la varianza mide qué tan volátil es una acción por sí sola.

In [12]:
returns = returns.dropna()

In [111]:
# Generamos pesos aleatorios para el portafolio que sumen 1
np.random.seed(42) 
weights = np.random.random(len(returns.columns))
weights = weights / np.sum(weights)
weights

array([0.12619616, 0.32033016, 0.24663533, 0.20170978, 0.05256834,
       0.05256022])

In [18]:
# Calculamos el rendimiento histórico del portafolio consolidado
returns['Portfolio'] = returns.dot(weights)
returns['Portfolio'].tail()

Date
2026-05-21   -0.000749
2026-05-22   -0.004970
2026-05-26    0.001394
2026-05-27    0.011201
2026-05-28   -0.000044
Name: Portfolio, dtype: float64

In [19]:
returns.tail()

Ticker,AAPL,AMZN,GOOGL,META,MSFT,NVDA,Portfolio
Date,,,,,,,
2026-05-21,0.009065,0.013018,-0.003214,0.003834,-0.002523,-0.017721,-0.000749
2026-05-22,0.012558,-0.007971,-0.012098,0.004742,-0.001241,-0.019042,-0.004970
2026-05-26,-0.001587,-0.003868,0.015432,0.003408,-0.006068,-0.002183,0.001394
2026-05-27,0.008173,0.024728,-0.000129,0.037430,-0.008076,-0.010518,0.011201
2026-05-28,-0.001641,-0.006217,0.000155,-0.006706,0.028255,0.004700,-0.000044

En la Teoría Moderna de Portafolios (de Harry Markowitz) el objetivo es proyectar en el futuro dos cosas fundamentales de un portafolio de inversión: cuánto dinero vas a ganar (Retorno) y cuánto riesgo estás asumiendo (Volatilidad/Desviación Estándar).

In [15]:
# Necesitamos los pesos de las acciones que compramos (weights), los rendimientos históricos promedio (mean_returns), 
# la matriz de covarianza (cov_matrix) y el horizonte de tiempo (time). 
# A partir de estos parámetros, calculamos el rendimiento esperado (expected_returns) y el riesgo del portafolio completo (std).

time = 100 
expected_returns = np.sum(mean_returns * weights) * time
std = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights))) * np.sqrt(time)

In [16]:
print("Rendimiento esperado del portafolio: ", expected_returns)
print("Riesgo del portafolio (desviación estándar): ", std)

Rendimiento esperado del portafolio:  0.2278941983752875
Riesgo del portafolio (desviación estándar):  0.15226113179051226

Al multiplicar el rendimiento promedio pasado por Time, estamos asumiendo matemáticamente el supuesto de que el futuro se va a comportar exactamente igual que el promedio del pasado. Aunque rendimientos pasados no garantizan rendimientos futuros. Es un "punto de partida" estándar: En estadística, ante la total imposibilidad de adivinar el futuro, el promedio histórico es matemáticamente el estimador menos sesgado que tenemos a la mano.

Si queremos que no sea una simple proyección lineal del pasado, se usan técnicas más avanzadas para simular un horizonte de tiempo. Simulaciones de Monte Carlo: En lugar de multiplicar por un horizonte de tiempo, usamos el promedio histórico y la covarianza como "reglas de juego" para que la computadora simule por ejemplo 10,000 futuros posibles diferentes día por día, añadiendo aleatoriedad (ruido estadístico). Al final, no obtenemos un solo número, sino una distribución de probabilidades _(ej. "Hay un 70% de probabilidad de que tu portafolio rinda entre tal y tal valor")_.

In [30]:
# Parámetros globales de la simulación

initial_investment = 10000 # Inversión inicial en dólares
alpha = 5 # Significancia del 5% (equivalente a 95% de confianza)

El VaR (Value at Risk) es una métrica que dice cuál es la pérdida máxima esperada para un nivel de confianza determinado (un parámetro alpha=0.05 indica 95% de confianza). Si alpha=5, significa que estamos buscando el peor 5% de los días de la historia de nuestro portafolio. Es decir, que tenemos un 95% de confianza de que las pérdidas no superarán ese número.

In [24]:
# a: son los datos
# q: es el percentil que queremos calcular, en este caso, el percentil del 5% (alpha)
var = np.percentile(a = returns['Portfolio'], q = alpha)
print(f"El VaR del portafolio al {100-alpha}% de confianza es: {-var:.2%}")

El VaR del portafolio al 95% de confianza es: 2.00%

Por pura convención. El VaR es, por definición, una métrica de pérdida. Como la palabra "pérdida" ya implica que el dinero va hacia abajo, dejar el signo negativo sería una doble negación (sería como decir "tengo una pérdida de -2%"). Convertirlo a un porcentaje positivo limpia la lectura del análisis.

In [27]:
below_var = returns['Portfolio'] <= var
print(below_var)

Date
2026-02-18    False
2026-02-19    False
2026-02-20    False
2026-02-23    False
2026-02-24    False
              ...
2026-05-21    False
2026-05-22    False
2026-05-26    False
2026-05-27    False
2026-05-28    False
Name: Portfolio, Length: 70, dtype: bool

El percentil 5 (alpha=5) corta esa fila exactamente en el punto donde se separa el 5% de los peores días del 95% de los días restantes.

El CVaR (Conditional Value at Risk también llamado Expected Shortfall) va un paso más allá del VaR. El VaR te dice dónde empieza la "zona de desastre", pero el CVaR te dice qué tan grave es el desastre una vez que cruzas la línea. Responde a: "Si tengo la mala suerte de caer en ese peor 5%, ¿cuál será la pérdida promedio?"

In [29]:
cvar = returns['Portfolio'][below_var].mean()
print(f"El CVaR del portafolio al {100-alpha}% de confianza es: {-cvar:.2%}")

El CVaR del portafolio al 95% de confianza es: 2.72%

el CVaR es el promedio de las peores pérdidas.

El VaR que calcula la función originalmente es diario (porque tus datos de rendimiento son diarios). Si quieres saber cuánta plata arriesgas a lo largo de un periodo más largo (por ejemplo, en un horizonte de Time = 100 días), multiplicas el VaR diario por la raíz cuadrada del tiempo, exactamente igual a como escalaste la volatilidad en la función anterior.

In [32]:
hVaR = var * np.sqrt(time)
hCVaR = cvar * np.sqrt(time)
print(f"El VaR histórico del portafolio al {100-alpha}% de confianza es: {-hVaR:.2%}")
print(f"El CVaR histórico del portafolio al {100-alpha}% de confianza es: {-hCVaR:.2%}")

El VaR histórico del portafolio al 95% de confianza es: 19.97%
El CVaR histórico del portafolio al 95% de confianza es: 27.16%

Interpretación:
 - "Tengo un 95% de confianza de que en los próximos 100 días no perderé más del 19% ($1900 USD) de mi dinero (si invierto $10_000 USD)".
 - "Sin embargo, si las cosas salen realmente mal y caigo en ese fatídico 5% de peores escenarios, la pérdida promedio que debo esperar es del 27% ($2700 USD)".

In [ ]:
# ==========================================
# 4. SIMULACIÓN DE MONTE CARLO
# ==========================================

mc_sims = 1000 # Incrementado a 1000 para mayor precisión matemática
T = time

meanM = np.full(shape=(T, len(weights)), fill_value=mean_returns).T
portfolio_sims = np.full(shape=(T, mc_sims), fill_value=0.0)

# Simulación de trayectorias con correlación de Cholesky
for m in range(0, mc_sims):
    Z = np.random.normal(size=(T, len(weights)))
    L = np.linalg.cholesky(cov_matrix)
    dailyReturns = meanM + np.inner(L, Z)
    portfolio_sims[:, m] = np.cumprod(np.inner(weights, dailyReturns.T) + 1) * initial_investment

# Funciones de riesgo para Monte Carlo
def mcVaR(returns, alpha=5):
    if isinstance(returns, pd.Series):
        return np.percentile(returns, alpha)
    else:
        raise TypeError("Se esperaba una serie de Pandas.")

def mcCVaR(returns, alpha=5):
    if isinstance(returns, pd.Series):
        belowVaR = returns <= mcVaR(returns, alpha=alpha)
        return returns[belowVaR].mean()
    else:
        raise TypeError("Se esperaba una serie de Pandas.")

# Extraemos los resultados del último día de la simulación
portResults = pd.Series(portfolio_sims[-1, :])

mc_VaR_val = initial_investment - mcVaR(portResults, alpha=alpha)
mc_CVaR_val = initial_investment - mcCVaR(portResults, alpha=alpha)

In [ ]:
# ==========================================
# 2. MÉTODO HISTÓRICO
# ==========================================

def historicalVaR(returns, alpha=5):
    if isinstance(returns, pd.Series):
        return np.percentile(returns, alpha)
    elif isinstance(returns, pd.DataFrame):
        return returns.aggregate(historicalVaR, alpha=alpha)
    else:
        raise TypeError("Se esperaba un DataFrame o Series de Pandas")

def historicalCVaR(returns, alpha=5):
    if isinstance(returns, pd.Series):
        belowVaR = returns <= historicalVaR(returns, alpha=alpha)
        return returns[belowVaR].mean()
    elif isinstance(returns, pd.DataFrame):
        return returns.aggregate(historicalCVaR, alpha=alpha)
    else:
        raise TypeError("Se esperaba un DataFrame o Series de Pandas")

# Calculamos y escalamos los valores históricos
hVaR = -historicalVaR(returns['portfolio'], alpha=alpha) * np.sqrt(Time)
hCVaR = -historicalCVaR(returns['portfolio'], alpha=alpha) * np.sqrt(Time)

In [ ]:
# ==========================================
# 5. DESPLIEGUE DE RESULTADOS Y GRÁFICO
# ==========================================

print("-" * 50)
print(f"REPORTES DE RIESGO FINANCIERO (Inversión: ${initial_investment:,} a {time} días)")
print("-" * 50)
print(f"Rendimiento Esperado del Portafolio : ${round(initial_investment * pRet, 2)}")
print("\n--- Métricas de Value at Risk (VaR 95%) ---")
print(f" Histórico VaR                      : ${round(initial_investment * hVaR, 2)}")
print(f" Paramétrico Normal VaR             : ${round(initial_investment * normVaR, 2)}")
print(f" Paramétrico t-Student VaR          : ${round(initial_investment * tVaR, 2)}")
print(f" Monte Carlo VaR                    : ${round(mc_VaR_val, 2)}")

print("\n--- Métricas de Conditional VaR (CVaR 95%) ---")
print(f" Histórico CVaR                     : ${round(initial_investment * hCVaR, 2)}")
print(f" Paramétrico Normal CVaR            : ${round(initial_investment * normCVaR, 2)}")
print(f" Paramétrico t-Student CVaR         : ${round(initial_investment * tCVaR, 2)}")
print(f" Monte Carlo CVaR                   : ${round(mc_CVaR_val, 2)}")
print("-" * 50)

# Generación del gráfico de Monte Carlo
plt.figure(figsize=(10, 6))
plt.plot(portfolio_sims, lw=0.5, alpha=0.6)
plt.axhline(initial_investment, color='black', linestyle='--', label='Inversión Inicial')
plt.ylabel('Valor del Portafolio ($)')
plt.xlabel('Días en el Futuro')
plt.title(f'Simulación de Monte Carlo ({mc_sims} escenarios a {T} días)')
plt.grid(True, alpha=0.3)
plt.show()

In [ ]:
# ==========================================
# 1. OBTENCIÓN DE DATOS Y CONFIGURACIÓN
# ==========================================

def getData(stocks, start, end):
    # Descargamos los datos usando yfinance 
    stockData = yf.download(stocks, start=start, end=end)
    stockData = stockData['Close']
    
    # Calculamos rendimientos diarios logarítmicos/porcentuales
    returns = stockData.pct_change()
    meanReturns = returns.mean()
    covMatrix = returns.cov()
    return returns, meanReturns, covMatrix

def portfolioPerformance(weights, meanReturns, covMatrix, Time):
    returns = np.sum(meanReturns * weights) * Time
    std = np.sqrt(np.dot(weights.T, np.dot(covMatrix, weights))) * np.sqrt(Time)
    return returns, std

# Definimos los activos más populares del S&P 500 (Mercado de EE. UU.)
stockList = ['MSFT', 'AAPL', 'NVDA', 'AMZN', 'META', 'GOOGL']
stocks = [stock for stock in stockList]

# Definimos la ventana de tiempo (800 días hacia atrás)
endDate = dt.datetime.now()
startDate = endDate - dt.timedelta(days=800)

# Descarga y limpieza
returns, meanReturns, covMatrix = getData(stocks, start=startDate, end=endDate)
returns = returns.dropna()

# Generamos pesos aleatorios para el portafolio que sumen 1
weights = np.random.random(len(returns.columns))
weights /= np.sum(weights)

# Calculamos el rendimiento histórico del portafolio consolidado
returns['portfolio'] = returns.dot(weights)

# Parámetros globales de la simulación
Time = 100 # Horizonte de tiempo en días
InitialInvestment = 10000 # Inversión inicial en dólares
alpha = 5 # Significancia del 5% (equivalente a 95% de confianza)

# Rendimiento y desviación estándar esperados del portafolio en el horizonte de tiempo
pRet, pStd = portfolioPerformance(weights, meanReturns, covMatrix, Time)

In [ ]:
# ==========================================
# 3. MÉTODO PARAMÉTRICO (Varianza-Covarianza)
# ==========================================

def var_parametric(portfolioReturns, portfolioStd, distribution='normal', alpha=5, dof=6):
    if distribution == 'normal':
        VaR = norm.ppf(1 - alpha/100) * portfolioStd - portfolioReturns
    elif distribution == 't-distribution':
        nu = dof
        VaR = np.sqrt((nu - 2) / nu) * t.ppf(1 - alpha/100, nu) * portfolioStd - portfolioReturns
    else:
        raise TypeError("Distribución no soportada. Use 'normal' o 't-distribution'")
    return VaR

def cvar_parametric(portfolioReturns, portfolioStd, distribution='normal', alpha=5, dof=6):
    if distribution == 'normal':
        CVaR = (alpha/100)**-1 * norm.pdf(norm.ppf(alpha/100)) * portfolioStd - portfolioReturns
    elif distribution == 't-distribution':
        nu = dof
        xanu = t.ppf(alpha/100, nu)
        CVaR = -1/(alpha/100) * (1 - nu)**(-1) * (nu - 2 + xanu**2) * t.pdf(xanu, nu) * portfolioStd - portfolioReturns
    else:
        raise TypeError("Distribución no soportada. Use 'normal' o 't-distribution'")
    return CVaR

# Cálculos Paramétricos
normVaR = var_parametric(pRet, pStd, distribution='normal', alpha=alpha)
normCVaR = cvar_parametric(pRet, pStd, distribution='normal', alpha=alpha)

tVaR = var_parametric(pRet, pStd, distribution='t-distribution', alpha=alpha, dof=6)
tCVaR = cvar_parametric(pRet, pStd, distribution='t-distribution', alpha=alpha, dof=6)